- rsb/botLauncher/ClassPreloader.java
- rsb/botLauncher/RuneLite.java
- rsb/botLauncher/RuneLiteTestFeatures.java
- rsb/gui/BotGUI.java
- rsb/gui/ClientPanel.java
- rsb/methods/GroundItems.java
- rsb/methods/MethodProvider.java
- rsb/wrappers/RSCharacterModel.java
- rsb/wrappers/RSItem.java
- rsb/wrappers/RSModel.java
The api should now be functional and able to start. It may still have incorrect IDs hard-coded in and poorly managed tidbits. This can be updated at a later time.
#20
> Repaired API to working status

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question-help.md
Adds the templates I added on GitHub to the WIP branch
> add templates to wip

- README.md
- rsb/botLauncher/RuneLite.java
- rsb/event/impl/TFPS.java
- rsb/gui/BotGUI.java
- rsb/internal/BotHooks.java
- rsb/internal/BotModule.java
- rsb/script/randoms/LoginBot.java
- rsb/testsScript/Test.java
Extended the RuneLite Hooks and overrided the draw method utilizing some reflection and doing so also prepped for creating future drawing functions.
Additionally fixed LoginBot _probably_. It was still failing to pass the Welcome screen prior to this.
> No More RuneLite Changes

- rsb/botLauncher/RuneLite.java
- rsb/testsScript/Test.java
Made small commits that left this one behind
> Update WIP Branch

- rsb/botLauncher/RuneLite.java
Proxy Support as suggested in #7
> Proxy Support

- rsb/script/randoms/LoginBot.java
It now intelligently determines whether you're logged in and how to go about hitting the play button
closes #37
> Fixed LoginBot

- rsb/botLauncher/RuneLite.java
- rsb/event/impl/DrawItems.java
- rsb/event/impl/DrawNPCs.java
- rsb/event/impl/DrawPlayers.java
- rsb/methods/Calculations.java
- rsb/methods/GroundItems.java
- rsb/wrappers/RSCharacterModel.java
- rsb/wrappers/RSGroundItem.java
- rsb/wrappers/RSGroundItemModel.java
- rsb/wrappers/RSModel.java
- rsb/wrappers/RSObject.java
- rsb/wrappers/RSObjectModel.java
Fixed SEVERAL issues with api from ground items being allowed to be grabbed from too far out to several calculations being blatantly wrong. More importantly this should fix most if not all interactions with models bar grounditems (they work, but aren't calculated at the correct height).
> Models are fixed and so is a bunch of back-end calculations

- rsb/botLauncher/Application.java
- rsb/botLauncher/RuneLite.java
- rsb/internal/BotModule.java
- rsb/methods/GroundItems.java
- rsb/methods/Inventory.java
- rsb/methods/Menu.java
- rsb/methods/Objects.java
- rsb/wrappers/RSCharacter.java
- rsb/wrappers/RSItem.java
- rsb/wrappers/RSNPC.java
- rsb/wrappers/RSObject.java
I got most of this working but how we handle args is different. 
I cant get the bot GUI the load without launching the Application from my IDE.
Think its messing up on  injector.getInstance(RuneLite.class).start();
Ours isn't public.
Also tried
java -ea -cp net.runelite.client.RuneLite -jar runelite-client-3.2.1-shaded.jar --bot-runelite
2020-04-06 19:26:03 [main] WARN  net.runelite.client.RuneLite - Error parsing launch args: bot-runelite is not a recognized option
Maybe you can figure out how to get support working for OpenOSRS, i'm not really a java coder. 
this also should be its own branch called openosrs
> WIP OpenOSRS support

- rsb/botLauncher/RuneLiteTestFeatures.java
- rsb/wrappers/RSModel.java
- rsb/wrappers/RSObject.java
- rsb/wrappers/RSWallObjectModel.java
Fixed model bug causing non-game objects from working (Wall objects aren't handled appropriately, but aren't broken. Right now they'll only ever go for the first model. Will look into fixing later.)
> Ladies and gentlemen, we got him.

- rsb/botLauncher/RuneLiteTestFeatures.java
- rsb/testsScript/Test.java
- rsb/wrappers/RSObject.java
Fixes the game objects returning null models and making the api do guesses on location based on the tile
closes #14
closes #48
> Small tweak

- rsb/wrappers/RSPlayer.java
Fixed the isMoving method for the local player
> One character fix

- rsb/botLauncher/RuneLiteTestFeatures.java
- rsb/internal/input/VirtualMouse.java
- rsb/testsScript/Test.java
- rsb/wrappers/RSArea.java
- rsb/wrappers/RSCharacter.java
- rsb/wrappers/RSPlayer.java
- rsb/wrappers/RSTile.java
Fixes the area contains on polygons (prior it might not work correctly if the polygon was weird, now it correctly handles border cases)
RSArea was also not properly taking in account plane when comparing causing issues
Updated a few bits of code
> General fixes

- rsb/botLauncher/RuneLiteTestFeatures.java
- rsb/gui/ScriptSelector.java
- rsb/methods/Game.java
- rsb/methods/Walking.java
- rsb/plugin/Botplugin.java
- rsb/testsScript/Test.java
- rsb/util/GlobalConfiguration.java
- rsb/wrappers/RSLocalPath.java
- rsb/wrappers/RSObject.java
- rsb/wrappers/RSTilePath.java
Fixes the collisionmap issue in walking and the issue with creating/running jar files
fixes #57
> Walking and Jar Compile Fix

- src/main/java/rsb/internal/globval/GlobalConfiguration.java
- src/main/java/rsb/plugin/BotPanel.java
- src/main/java/rsb/plugin/ScriptPanel.java
> Add Scripts Folder and Forums button to scripts panel

- src/main/java/rsb/internal/InputManager.java
- src/main/java/rsb/internal/globval/GlobalConfiguration.java
Fixed the wonderful mouse issue.
Turns out > 0 is not going to allow movement to 0. Who would've thought.
Also added some code revisions for GlobalConfiguration as well as more method documentation.
> Bug fix and optimizations

- .idea/inspectionProfiles/Project_Default.xml
- src/main/java/rsb/botLauncher/RuneLite.java
- src/main/java/rsb/internal/InputManager.java
- src/main/java/rsb/internal/input/VirtualKeyboard.java
- src/main/java/rsb/internal/input/VirtualMouse.java
- src/main/java/rsb/methods/Camera.java
We get it. Jagex should probably not use a part of a library that was deprecated for security flaws. We know. Thank you, IntelliJ.
> Fixes the annoying build error spam

- README.md
Discord is a great place for questions to be lost then re-asked
> Add forums link to README

- src/main/java/rsb/internal/NewHooks.java
- src/main/java/rsb/service/Monitoring.java
- src/main/java/rsb/wrappers/RSWidget.java
> Remove waste code from wrappers

- src/main/java/net/runelite/rsb/wrappers/client_wrapper/RSClient.java
was being caused by RSClient lacking getSceneMax
> Fixes the jitpack error

- src/main/java/net/runelite/client/modified/BotModule.java
- src/main/java/net/runelite/rsb/botLauncher/Application.java
- src/main/java/net/runelite/rsb/internal/globval/GlobalWidgetInfo.java
- src/main/java/net/runelite/rsb/internal/globval/WidgetIndices.java
- src/main/java/net/runelite/rsb/methods/Interfaces.java
- src/main/java/net/runelite/rsb/wrappers/RSWidgetItem.java
- src/main/java/net/runelite/rsb/wrappers/client_wrapper/BaseClientWrapper.java
- src/main/java/net/runelite/rsb/wrappers/client_wrapper/BaseWidgetWrapper.java
- src/main/java/net/runelite/rsb/wrappers/client_wrapper/RSClient.java
- src/main/java/net/runelite/rsb/wrappers/common/CacheProvider.java
- src/main/java/net/runelite/rsb/wrappers/subwrap/NPCChat.java
Update NPCChat to work with more widgets and extend the interface.
>  Update NPCChat to work with more widgets and extend the interface.

- src/main/java/net/runelite/client/modified/BotModule.java
- src/main/java/net/runelite/rsb/botLauncher/Application.java
- src/main/java/net/runelite/rsb/methods/Inventory.java
- src/main/java/net/runelite/rsb/wrappers/RSWidgetItem.java
- src/main/java/net/runelite/rsb/wrappers/client_wrapper/BaseClientWrapper.java
- src/main/java/net/runelite/rsb/wrappers/client_wrapper/BaseWidgetWrapper.java
- src/main/java/net/runelite/rsb/wrappers/client_wrapper/RSClient.java
- src/main/java/net/runelite/rsb/wrappers/common/CacheProvider.java
Add isOpen and open to inventory
> Open inventory

- src/main/java/net/runelite/rsb/wrappers/RSGroundObjectModel.java
- src/main/java/net/runelite/rsb/wrappers/RSModel.java
Change how RSModel handles objects without a model
> Rs model no model

- src/main/java/net/runelite/rsb/methods/Menu.java
- src/main/java/net/runelite/rsb/wrappers/RSCharacter.java
- src/main/java/net/runelite/rsb/wrappers/RSGroundItem.java
- src/main/java/net/runelite/rsb/wrappers/RSObject.java
- src/main/java/net/runelite/rsb/wrappers/RSPlayer.java
Make menu action targets actually work.
> Menu action targets

- src/main/java/net/runelite/rsb/wrappers/RSTile.java
Apparently this fix never got into a commit?
> RSTile getSceneX() and getSceneY() Fix

- src/main/java/net/runelite/rsb/script/PassiveScript.java
- src/main/java/net/runelite/rsb/script/Script.java
- src/main/java/net/runelite/rsb/service/ScriptClassLoader.java
Allows Script and PassiveScript to subscribe to the runelite event but in BotLite by annotation their functions with @Subscribe
> Subscribe runelite events

- src/main/java/net/runelite/rsb/internal/globval/WidgetIndices.java
- src/main/java/net/runelite/rsb/script/randoms/LoginBot.java
- src/main/java/net/runelite/rsb/wrappers/RSWidget.java
I updated some widget ids. Notably also the LoginBot now works again as that widget id was also outdated. I've left out some of the settings tab widget ids as those widgets are really not important (sprite widgets) and will most likely not be used by anyone. I also changed the naming convention to be less confusing. Usually you shouldn't change the names as existing scripts will break. But since this is very outdated I assume nobody is using them at the moment.
> Widget fixes

- src/main/java/net/runelite/rsb/methods/Tiles.java
> Add alternate methods::Tiles::getTile()

- build.gradle
- src/main/java/net/runelite/client/callback/Hooks.java
- src/main/java/net/runelite/rsb/internal/globval/GlobalWidgetInfo.java
- src/main/java/net/runelite/rsb/methods/Calculations.java
- src/main/java/net/runelite/rsb/methods/Chat.java
- src/main/java/net/runelite/rsb/methods/MethodContext.java
- src/main/java/net/runelite/rsb/methods/Methods.java
- src/main/java/net/runelite/rsb/wrappers/RSNPC.java
- src/main/java/net/runelite/rsb/wrappers/client_wrapper/BaseClientWrapper.java
> various fixes

- src/main/java/net/runelite/rsb/internal/InputManager.java
- src/main/java/net/runelite/rsb/internal/MouseHandler.java
some of the modifications needed to access/change the default mouse behavior as well as interact with MouseMotionFactory (ie: using our own settings / profiles).
> added accessors to MouseMotionFactory
